### ISSUE TITLE
Support common identifiers

### ISSUE THREAD

**Issue by marci4** [thilojaeggi/WinGetty#50]
**Is your feature request related to a problem? Please describe.**
Most identifiers in the current winget repository contain "special" characters, which will currently be removed when adding a package via the UI (https://github.com/thilojaeggi/WinGetty/blob/main/app/templates/modals/add_package.j2#L63)

**Describe the solution you'd like or how it could be implemented**
Support common identifiers containing ("+","-",".""_")

**Additional context**
Examples:
`Notepad++.Notepad++`
`ndd.Notepad--`
` Zheguisoft.zg_mdm`

**Comment by marci4** [comment]
I would love to help you here, if you can maybe explain why you changed https://github.com/thilojaeggi/WinGetty/commit/8f1cdbf303c1215f8ea1bf3ae926ca4e494e7aea

**Comment by thilojaeggi** [comment]
Hi marci4

Iirc this was done in an attempt to remove special characters from the Identifier as these would get stripped later by "secure_filename" in the backend. Although I think "+" amongst others should be safe from this and the regex could be changed.

**Comment by thilojaeggi** [comment]
Fixed in:
9870372faf707d61832ee3feb5ff3385a92c2538
0bb9ccb506a719ed399aa911b3f0261b952439c8
7dcc8f1c884446ad2f399fcfa32cbbf8aacee6ca

**Comment by marci4** [comment]
Works after updating to the current dev.
Thank you @thilojaeggi  for the quick fix.

**Comment by thilojaeggi** [comment]
Just fyi, it is *not* recommended to use the dev branch as it will break things.

**Comment by marci4** [comment]
Sorry I have to reopen the issue.
It is still not possible to upload a package name with an identifier like "Microsoft.DotNet.SDK.8"
